schemaVersion: 2.2.0
metadata:
  name: ace-bdd-cucumber
projects:
  - name: ace-bdd-cucumber
    git:
      remotes:
        origin: 'https://github.com/tdolby-at-uk-ibm-com/ace-bdd-cucumber'
      checkoutFrom:
        revision: main
components:
  - name: ace-v12
    container:
      image: 'tdolby/experimental:ace-dev-spaces-container-xvnc-12.0.8.0'
      memoryLimit: 2048Mi
      cpuLimit: 1000m
      env:
        - name: LICENSE
          value: accept
      mountSources: true
