apiVersion: 1.0.0
metadata:
  name: ace-bdd-cucumber
projects:
  - name: ace-bdd-cucumber
    source:
      type: git
      location: 'https://github.com/tdolby-at-uk-ibm-com/ace-bdd-cucumber'
components:
  - alias: ace-v12
    type: dockerimage
    image: 'tdolby/experimental:ace-dev-spaces-container-xvnc-12.0.7.0'
    memoryLimit: 2048Mi
    env:
      - name: LICENSE
        value: accept
    endpoints:
      - name: server
        port: 7600
        attributes:
          discoverable: 'true'
          public: 'true'
          protocol: 'http'
      - name: novnc
        port: 6080
        attributes:
          discoverable: 'true'
          public: 'true'
          protocol: 'http'
    mountSources: true
